language: java

jdk:
  - oraclejdk8

script: 
  - mvn cobertura:cobertura -Dspring.profiles.active=tests

notifications:
  email:
    recipients:
      - leonardomdeoli@gmail.com
    on_success: never
    on_failure: always
  
after_success:
  - bash <(curl -s https://codecov.io/bash)